version: '3.8'

services:
  # Database Services
  mongodb:
    image: mongo:7.0
    container_name: saas-billing-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: saas_billing
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - saas-billing-network

  # Redis for Message Queue
  redis:
    image: redis:7.2-alpine
    container_name: saas-billing-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas-billing-network

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: saas-billing-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CUSTOMER_SERVICE_URL=http://customer-service:3001
      - AUTH_SERVICE_URL=http://auth-service:3005
      - SUBSCRIPTION_SERVICE_URL=http://subscription-service:3002
      - PLAN_SERVICE_URL=http://plan-service:3003
      - INVOICE_SERVICE_URL=http://invoice-service:3004
    depends_on:
      - customer-service
      - auth-service
      - subscription-service
      - plan-service
      - invoice-service
    networks:
      - saas-billing-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: saas-billing-auth
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/saas_billing?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here
      - AUTH0_DOMAIN=your-domain.auth0.com
      - AUTH0_CLIENT_ID=your-client-id
      - AUTH0_CLIENT_SECRET=your-client-secret
    depends_on:
      - mongodb
    networks:
      - saas-billing-network

  # Customer Service
  customer-service:
    build:
      context: ./services/customer-service
      dockerfile: Dockerfile
    container_name: saas-billing-customer
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/saas_billing?authSource=admin
      - AUTH_SERVICE_URL=http://auth-service:3005
    depends_on:
      - mongodb
      - auth-service
    networks:
      - saas-billing-network

  # Subscription Service
  subscription-service:
    build:
      context: ./services/subscription-service
      dockerfile: Dockerfile
    container_name: saas-billing-subscription
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/saas_billing?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here
      - CUSTOMER_SERVICE_URL=http://customer-service:3001
      - PLAN_SERVICE_URL=http://plan-service:3003
    depends_on:
      - mongodb
      - customer-service
      - plan-service
    networks:
      - saas-billing-network

  # Plan Service
  plan-service:
    build:
      context: ./services/plan-service
      dockerfile: Dockerfile
    container_name: saas-billing-plan
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    networks:
      - saas-billing-network

  # Invoice Service
  invoice-service:
    build:
      context: ./services/invoice-service
      dockerfile: Dockerfile
    container_name: saas-billing-invoice
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - JWT_SECRET=your-super-secret-jwt-key-here
      - CUSTOMER_SERVICE_URL=http://customer-service:3001
      - SUBSCRIPTION_SERVICE_URL=http://subscription-service:3002
    depends_on:
      - customer-service
      - subscription-service
    networks:
      - saas-billing-network

volumes:
  mongodb_data:
  redis_data:

networks:
  saas-billing-network:
    driver: bridge 